### ISSUE TITLE
can you update bot reaction for new reaction (CARE reaction)?

### ISSUE THREAD

**Issue by MujurID** [J2TeamNNL/J2Team-Community#4]
can you update bot reaction for new reaction (CARE reaction)? newfeed. this clue
use cookie (please don't make login input user&pass beacuse make checkpoint), maybe can user "cookie.txt" extension for get cookie.txt for use
use https://m.facebook.com/ufi/reaction/?ft_ent_identifier= ..... &reaction_type={this number id for reaction like = 1, love = 2, wow = 3, haha = 4, sad = 7, angry = 8, care = 16} .....

if you use access_token
if use https://graph.facebook.com ..... /reactions?
can't be used for new reaction (CARE reaction)

sorry for very bad english

**Comment by J2TeamNNL** [comment]
Yeah, I can see what you mean, but I think that Facebook will remove this reaction soon

And I make tool for PHP cronjob, maybe I will create extension later, in another version

Thank for your opinion and take care
